### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by simon-vajda** [akosbordas/ncore-client#1]
Nagyon hasznos a könyvtár :) de egy ideje ezt a hibát kapom, ha használni szeretném:
`javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version`

Lehetséges megoldás:
A HttpClientProvider osztályban TLSv1.2-t kéne használni a kapcsolat létrehozásához.

**Comment by akosbordas** [comment]
Koszi szepen, ez valoban hiba volt. Ki is javitottam. :) Egy ideje mar nem releaseltem, amint megtalalom  a Sonatype PK-mat fogok is csinalni egy ujabbat! :D Koszi meg1x hogy jelezted.

**Comment by akosbordas** [comment]
Az RC3-as verzioban benne lesz a fix. Mar releaseltem, par nap es bent lesz.
